name: Build main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Patch Airplane
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          ./gradlew applyPatches
          ./gradlew build
          ./gradlew paperclip

      - uses: actions/upload-artifact@v2
        with:
          name: Airplane-JDK${{ matrix.java }}
          path: launcher-airplanepurpur.jar

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: "always() && needs.build.result != 'skipped'"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send webhook
        run: |
          git clone https://github.com/Encode42/discord-workflows-webhook.git webhook
          bash webhook/send.sh ${{ needs.build.result }} ${{ secrets.WEBHOOK_URL }}
        shell: bash
